
version: '3'

volumes:
  gogs:
  pg:
  www:
  drone:
networks:
  www:
  postgres:
  drone:

services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./data/log/nginx:/var/log/nginx
      - ./conf/nginx/conf.e:/etc/nginx/conf.d
      - www:/www
    networks:
      www:
        aliases:
          - www

  postgres:
    image: chenxinaz/pg_jieba:alpine
    environment:
      - POSTGRES_PASSWORD=asdfasdf123
    volumes:
      - pg:/var/lib/postgresql/data
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      postgres:
        aliases:
          - postgres

  gogs:
    image: gogs/gogs
    volumes:
      - gogs:/data
    networks:
      www:
        aliases:
          - gogs
      postgres:
        aliases:
          - gogs 

  drone-server:
    image: drone/drone
    volumes:
      - drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone.xin.me
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=http://gogs:3000
      - DRONE_SECRET=c676-9241-d916-3d6a
    networks:
      www:
        aliases:
          - drone 
      postgres:
        aliases:
          - drone 
      drone:
        aliases:
          - drone-server

  drone-agent:
    image: drone/agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=c676-9241-d916-3d6a
    networks:
      drone:
        aliases:
          - drone-agent
