
version: '3'

volumes:
  gogs:
  pg:
  www:
  drone:
networks:
  www:
  postgres:
  drone:

services:
  www:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./data/log/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - www:/www
    depends_on:
      - drone-server
      - gogs
    networks:
      www:

  postgres:
    image: chenxinaz/pg_jieba:alpine
    environment:
      - POSTGRES_PASSWORD=asdfasdf123
    volumes:
      - pg:/var/lib/postgresql/data
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      postgres:

  gogs:
    image: gogs/gogs
    volumes:
      - gogs:/data
    depends_on:
      - postgres
    networks:
      www:
      postgres:

  drone-server:
    image: drone/drone
    volumes:
      - drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone.xin.me
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs.xin.me
      - DRONE_SECRET=c676-9241-d916-3d6a
    networks:
      www:
      postgres:

  drone-agent:
    image: drone/agent
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=c676-9241-d916-3d6a
    networks:
      www:
