version: '3'

volumes:
  gogs:
  pg:
  gitea:
  www:
  jenkins:
networks:
  www:
  postgres:

services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - www:/www
    networks:
      www:
        aliases:
          - www.xin.me
          - xin.me
          - gogs.xin.me
          - gitea.xin.me
          - jenkins.xin.me
  postgres:
    image: chenxinaz/pg_jieba:alpine
    environment:
      - POSTGRES_PASSWORD=asdfasdf123
    volumes:
      - pg:/var/lib/postgresql/data
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      postgres:
  gogs:
    image: gogs/gogs
    volumes:
      - gogs:/data
    networks:
      www:
      postgres:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    volumes:
      - jenkins:/var/jenkins_home
      - www:/www
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      www:
  gitea:
    image: gitea/gitea
    volumes:
      - gitea:/data
    networks:
      www:
      postgres:
