version: '3'
services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - www:/www
    links:
      - gogs
  db:
    image: chenxinaz/pg_jieba:alpine
    environment:
      - POSTGRES_PASSWORD=asdfasdf123
    volumes:
      - pg:/var/lib/postgresql/data
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  gogs:
    image: gogs/gogs
    ports:
      - "3000:3000"
    volumes:
      - gogs:/data
    links:
      - db
  jenkins:
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8080:8080"
    volumes:
      - jenkins:/var/jenkins_home
volumes:
  gogs:
  pg:
  www:
  jenkins:
