version: '3'

networks:
  www:

services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    networks:
      www:
  gitea:
    image: gitea/gitea
    volumes:
      - ./data/gitea:/data
    networks:
      www:
