version: '3'

volumes:
  pg:
  gitea:
  www:
networks:
  www:
  postgres:

services:
  www:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - www:/www
    networks:
      www:
    restart: unless-stopped
  postgres:
    image: chenxinaz/pg_jieba:alpine
    environment:
      - POSTGRES_PASSWORD=W0FyHnAkc1JTgQMKocSByUCHtfnpuO8ZCGkdX+rheW0=
    volumes:
      - pg:/var/lib/postgresql/data
      - ./conf/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      postgres:
    restart: unless-stopped
  gitea:
    image: gitea/gitea
    volumes:
      - gitea:/data
    networks:
      www:
      postgres:
    restart: unless-stopped
