#!/bin/bash

# scripts with name like "git-*" can be executed by git.
# simply copy this file to execute path, e.g. /usr/bin,
# then we can do "git pushall"
# the only thing required was name this script with "git-*"

branch=${@:-$(git branch | grep \* | cut -d ' ' -f2)}

echo -e "\ndropping history of $branch....."

git checkout --orphan tmp

git commit -m "drop history"

git branch -D ${branch}

git branch -m ${branch}

echo -e "\nDone. You have push -f to repositories"
echo -e "\ne.g. git pushall ${branch}"
